#!/usr/bin/env bash

# ==============================================================================
# Program:       decrypt
# Description:   Encrypt files using gpg
# Software/Tool: gpg
# ==============================================================================

for file in $NAUTILUS_SCRIPT_SELECTED_URIS; do
    FILENAME="${@}"
    BASENAME="${FILENAME%.*}"
    EXT="${FILENAME##*.}"

    case "${EXT}" in
        asc|gpg)
            echo 'file encrypted'
        ;;
        *)
            kitty gpg --no-symkey-cache -ac "${FILENAME}"
        ;;
    esac
done
