#!/usr/bin/env bash

# this method sanitize path
WORK_DIR=$(echo "$NAUTILUS_SCRIPT_CURRENT_URI" | sed -e 's/%/\\x/g' -e 's_^file://__' | xargs -0 printf "%b")
META_DIR=$(echo "$NAUTILUS_SCRIPT_CURRENT_URI" | sed -e 's/%/\\x/g' -e 's_^file://__' -e 's/musics\|archived\|disposable/metadata/' | xargs -0 printf "%b")
FILENAME="${META_DIR}/info.toml"

if [[ -f "${FILENAME}" ]]; then
    echo "${FILENAME}"
    kitty -d "${META_DIR}" nvim info.toml
fi

