context.modules = [
    {
        name = libpipewire-module-combine-stream
        args = {
            combine.mode = sink
            node.name = "mono_sink"
            node.description = "Mono Output"
            combine.latency-compensate = false

            combine.props = {
                audio.position = [ MONO ]
                channel.mix = 0.707
                volume.control = false
            }

            stream.rules = [
                {
                    matches = [
                        {
                            media.class = "Audio/Sink"
                            node.name = "~alsa_output.*analog-stereo"
                        }
                    ]
                    actions = {
                        create-stream = {
                            audio.position = [ FL FR ]
                            combine.audio.position = [ MONO ]
                        }
                    }
                }
            ]
        }
    }
]
